spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor: TRACE